# Generated by Django 5.0.3 on 2024-03-07 03:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="contact_number",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Contact number must contain only numeric characters.",
                        regex="^\\d{1,15}$",
                    )
                ],
                verbose_name="Contact Number",
            ),
        ),
    ]
