# Generated by Django 5.0.3 on 2024-03-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=100, null=True, verbose_name="Title"),
        ),
    ]
