# Generated by Django 5.0.3 on 2024-03-06 16:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("categorie", "0002_product_profile_picture"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="profile_picture",
            new_name="picture",
        ),
    ]
